
name: gRPC Protobuf Distribute
on: 
  push:
    branches:
      - test/*
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22' # Specify the Go version
        
    - name: Setup Python 
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10'

    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        
    - name: Install gRPC Requirements
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        python -m pip install --upgrade pip
        python -m pip install grpcio grpcio-tools
      
    - name: Compile gRPC
      run: make all

    - name: Commit gRPC code to Proto-Go
      uses: CraftyLlamaCoalition/compile-grpc-action@main
      with: 
        language: go
        out_repo: CraftyLlamaProto-Go
        token: ${{ secrets.ORG_PAT_LARSON }}
        
    - name: Commit gRPC code to Proto-Python
      uses: CraftyLlamaCoalition/compile-grpc-action@main
      with: 
        language: python
        out_repo: CraftyLlamaProto-Python
        token: ${{ secrets.ORG_PAT_LARSON }}
          
  
